name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları klonla
        uses: actions/checkout@v3

      - name: JDK Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle'ı çalıştırılabilir yap
        run: chmod +x ./gradlew

      - name: Gradle ile derle
        run: ./gradlew assembleDebug

      - name: APK yolunu göster
        run: ls -alh app/build/outputs/apk/debug/
