      - name: APK dosyasını yükle
        uses: actions/upload-artifact@7b8d97bdc8cd27a9e3c7d6e6d9a44ed4d8b0e327  # v2 karşılığı SHA
        with:
          name: MuCuteClient-APK
          path: app/build/outputs/apk/debug/app-debug.apk
