name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları klonla
        uses: actions/checkout@v3

      - name: JDK Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle'ı çalıştırılabilir yap
        run: chmod +x ./gradlew

      - name: Gradle ile derle
        run: ./gradlew assembleDebug

      - name: APK'yi kopyala
        run: |
          mkdir -p apk
          cp app/build/outputs/apk/debug/app-debug.apk apk/MuCuteClient.apk

      - name: Değişiklikleri Git'e ekle
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add apk/MuCuteClient.apk
          git commit -m "APK otomatik yüklendi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
